### ISSUE TITLE
charts with convert issues

### ISSUE THREAD

**Issue by magiruuvelvet** [TsFreddie/KSHConvertFix#1]
Reporting issues I found in converts. I will update the list as I find more issues.

- [x] **キミヱゴサーチ** `INF` (lasers are partly broken across the entire chart)
- [x] **Bad Apple!!** `INF` (lasers are partly broken across the entire chart, most noticeable is the beginning)
- [x] **いーあるふぁんくらぶ** `GRV`

Had more charts already on the list but didn't wrote down their name. All I remember is that only the lasers are broken, buttons are totally fine.

EDIT: I'm using KSM 1.70a

**Comment by TsFreddie** [comment]
high resolution lasers getting interpreted as slams by KSM is expected. Keep the charts report coming! 

I will try to fix them manually until I found a way to automatically detect and interpolate them.

edit: might be more complicated to solve this on the converter side. pleaae wait patiently.

**Comment by magiruuvelvet** [comment]
> high resolution lasers getting interpreted as slams by KSM is expected

Didn't knew that, you learn something new every day :)

Well anyway, take your time. Once I found other charts with issues I will instantly update the list above - and if I figured out how to use the editor I may try to fix some of the charts myself. I had lots of trouble with the editor in the past.

**Comment by TsFreddie** [comment]
An update pack has been released. Should fix all three charts you mentioned as well as other charts with similar features.

**Comment by magiruuvelvet** [comment]
Woah that was quick. Indeed the issues with lasers are now fixed. Thanks :)
