### ISSUE TITLE
Laser audio issue with Destroy - Yooh

### ISSUE THREAD

**Issue by Shishiwaka** [TsFreddie/KSHConvertFix#2]
Audio goes silent during certain laser segments of destroy_yooh in SDVX III. Tested with EXH and GRV on USC

**Comment by TsFreddie** [comment]
Seems like USC has trouble with their laser DSP with low mix value. This chart is designed this way, so increasing effect volume in the charts will break the chart on KSM.

#### Solution:

For now, you can open both ksh file and replace

`#define_filter ft6 type=Echo;waveLength=0.031250;feedbackLevel=90%;mix=0%>51%;updatePeriod=0`

around the end of the file with:

`#define_filter ft6 type=Echo;waveLength=0.031250;feedbackLevel=90%;mix=0%>99%;updatePeriod=0`

However, if this is still too quiet for you. You can replace it with a BitCrusher which I think sounds pretty nice as well:

`#define_filter ft6 type=BitCrusher;reduction=0samples-10samples`

**Comment by TsFreddie** [comment]
Charts modified with BitCrusher laser FX has been uploaded.

**Comment by Shishiwaka** [comment]
Yeah, the BitCrusher is a better fix than the first one. Not AC accurate, but it works I suppose.
