### ISSUE TITLE
Random missing FX in USC and/or KSM

### ISSUE THREAD

**Issue by Shishiwaka** [TsFreddie/KSHConvertFix#3]
Noticed some songs in the II folder had some FX notes without an effect to them. These were the few I noticed on EXH so far
kiritorisen_40mp
torinokocity_40mp
zenmai_koi_dokei_aone
I believe KSM had less than USC, though I noticed a blank with both on ゼンマイ恋時計 T.E.B Summer Mix.

**Comment by TsFreddie** [comment]
```
kiritorisen_40mp
torinokocity_40mp
```
Can't find any problem with these charts. But they do use a lot of Flanger effects which sound already pretty subtle in KSM. But seems like USC is more subtle than KSM. The charts are fine. Flanger is not a timing-critical effect anyway.

```
zenmai_koi_dokei_aone
```
I can fix that one.
